# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error
import numpy as np
import joblib
import os

# === Load data ===
data = pd.read_csv('/content/crude_oil_macro_data.csv')
data['Date'] = pd.to_datetime(data['Date'])
data.set_index('Date', inplace=True)

# === Select target variable ===
target = data['Crude_Oil_Price'].dropna()

# === Split data ===
split_point = int(len(target) * 0.8)
train, test = target[:split_point], target[split_point:]

# === Train ARIMA model ===
model = ARIMA(train, order=(5, 1, 0))
model_fit = model.fit()

# === Forecast ===
forecast = model_fit.forecast(steps=len(test))

# === Evaluate ===
mse = mean_squared_error(test, forecast)
print(f"\n\u2705 ARIMA Model MSE: {mse:.2f}")

# === Save model ===
os.makedirs("models", exist_ok=True)
joblib.dump(model_fit, "arima_model.pkl")

# === Plot ===
plt.figure(figsize=(12, 5))
plt.plot(train.index, train, label='Train')
plt.plot(test.index, test, label='Test')
plt.plot(test.index, forecast, label='Forecast')
plt.legend()
plt.title("ARIMA Forecast vs Actual")
plt.savefig("models/arima_forecast_plot.png")
plt.show()